data scraper, collected data
kashubian-translator/pl-csb-data pull request #4
Opened 2024-06-08 09:56 UTC by Noxxxxious

2024-06-08 10:10 UTC, Karakean approved these changes

2024-06-08 14:38 UTC, filip-szweda requested changes

2024-06-08 14:38 UTC, filip-szweda commented on scrapers/declension.py
> +import re
> Imports should be grouped in the following order:
>     Standard library imports.
>     Related third party imports.
>     Local application/library specific imports.

https://peps.python.org/pep-0008/#imports

2024-06-08 14:38 UTC, filip-szweda commented on scrapers/declension.py
> +api_url = "https://sloworz.org/api/graphql"
```suggestion
API_URL = "https://sloworz.org/api/graphql"
```
https://peps.python.org/pep-0008/#constants

2024-06-08 14:38 UTC, filip-szweda commented on scrapers/declension.py
> +def fetch_polish_noun_declension(noun):
Add type hints to any and all function parameters as well as their returns.
https://peps.python.org/pep-0484/

2024-06-08 14:38 UTC, filip-szweda commented on scrapers/declension.py
> +    noun = noun.strip()
```suggestion
    stripped_noun = noun.strip()
```

2024-06-08 14:38 UTC, filip-szweda commented on scrapers/declension.py
> +    encoded_noun = quote(noun)
```suggestion
    quoted_noun = quote(noun)
```

2024-06-08 14:38 UTC, filip-szweda commented on scrapers/declension.py
> +    # Remove any integer within parentheses, including the parentheses
Instead of comments, you could create three helper functions e.g. `remove_integer_with_parentheses`, `remove_parentheses`, `remove_square_brackets`.

2024-06-08 14:38 UTC, filip-szweda commented on scrapers/declension.py
> +    for meaning in meanings:
Please use helper functions, Python code shouldn't be as nested.

2024-09-03 18:27 UTC, filip-szweda commented on scrapers/declension.py
> +    if not declension_table:
```
print("ERROR: Failed to find declension table in parsed html")
```

2024-09-03 18:27 UTC, filip-szweda commented on scrapers/declension.py
> +    if response.status_code != 200:
```
print(f"ERROR: Received status code {response.status_code}")
```

2024-09-03 18:27 UTC, filip-szweda commented on scrapers/declension.py
> +    declension_dict = {
```suggestion
    declension_dict = {
  "nounVariation": {
    "nominative": "",
    "genitive": "",
    "dative": "",
    "accusative": "",
    "instrumental": "",
    "locative": "",
    "vocative": "",
    "nominativePlural": "",
    "genitivePlural": "",
    "dativePlural": "",
    "accusativePlural": "",
    "instrumentalPlural": "",
    "locativePlural": "",
    "vocativePlural": ""
  }
}
```

2024-09-03 18:27 UTC, filip-szweda commented on scrapers/declension.py
> +    case_mapping = {
```suggestion
    case_mapping = {
  'Mianownik': 'nominative',
  'Dopełniacz': 'genitive',
  'Celownik': 'dative',
  'Biernik': 'accusative',
  'Narzędnik': 'instrumental',
  'Miejscownik': 'locative',
  'Wołacz': 'vocative'
}
```

2024-09-03 18:27 UTC, filip-szweda commented on scrapers/declension.py
> +    rows = declension_table.find_all('tr')[1:]  # skip header row
```
from bs4.element import Tag

...

def get_table_rows_excluding_header(table: Tag) -> Tag:
    return table.find_all("tr")[1:]
```
```suggestion
    rows = get_table_rows_excluding_header(declension_table)
```

2024-09-03 18:27 UTC, filip-szweda commented on scrapers/declension.py
> +        'Mianownik': 'nominative',
Replace all `'` with `"`.

2024-09-07 11:31 UTC, filip-szweda commented on scrapers/declension.py
> +    for word_meaning in word_meanings:
Create `KashubianEntryParser` with following methods:
`parse_word_meanings`
`parse_word_polish_translations`
`parse_noun_variations`
`parse_word_variations`
`parse_word_variation_variations`

2024-09-13 20:49 UTC, closed without merging